
library(igraph)

#********************* Declare functions*************************
# This function creates an ER random graph of N vertices with
# probability lambda/N
ER_graph <- function(N, lambda){
  pN = lambda/N #probability of adding an edge between vertex pair
  #print(pN)
  #create empty graph with N vertices and no edges
  g <- make_empty_graph(n = N, directed = FALSE)
  
  for (i in seq(1,N-2)) {
    for (j in seq(i+1,N)) {
      if (runif(1) <= pN) {
        g <- add_edges(g, c(i,j))
      }
    }
  }
  #plot(g)
  return(g)
}

# This function gets the number of edges in an ER random graph of size
# N generated by varying lambdas
get_n_edges <- function(start, end, step){
  n_edges <- vector(length = length(seq(start, end, step)))
  j <- 1
  for (i in seq(start, end, step)) {
    ER <- ER_graph(N = 100, lambda = i)
    n_edges[j] <- length(E(ER))
    j <- j + 1
  }
  
  d_n_edges <- data.frame(lambda = seq(start, end, step), n_edges = n_edges)
  return(d_n_edges)
}